import type { Metadata } from "next";
import "./globals.css";
import { CountdownProvider } from './context/CountdownContext';


export const metadata: Metadata = {
  title: "Virtual health",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Manually load Google Fonts Inter and Roboto Mono */}
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&family=Roboto+Mono&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <CountdownProvider >
                      {children}
        </CountdownProvider>
      </body>
    </html>
  );
}
