const newDatas = [
    {
        Name: "luxeGlow" ,
        fName: "l",
        id:1,
        amount:1,
        img:"UpdatedImg/f6947e640421d97017f27f6e9f08db61.jpg",
        price:`${34}$`,
        color:"black",
        time:"new",
        type:"others"
    },
    {
        Name: "aquaBreeze",
        fName: "a",
        id:2,
        amount:1,
        price:`${45}$`,
        img:"UpdatedImg/3b4f53031a9a6e897459671d3fa34207.jpg",
        color:"others",
        type:"hoddies",
        time:"old"
    },
    {
        Name: "zenTech",
        fName: "z",
        id:3,
        amount:1,
        price:`${80}$`,
        img:"UpdatedImg/4f62a31dbb3546a3ca38dc840508a04a.jpg",
        color:"white",
        type:"shouse",
        time:"new",
    },
    {
        Name: "novaFlex"  ,
        fName: "n",
        id:4,
        amount:1,
        price:`${76}$`,
        img:"UpdatedImg/7a03ad49d5707a25d357279a6d86cb31.jpg",
        color:"black",
        type:"hoddies",
        time:"old"
    },
    {
        Name: "ecoPure"  ,
        fName: "e",
        id:5,
        amount:1,
        price:`${124}$`,
        img:"UpdatedImg/8f81f44b0befd4190f24aa47f6dd99e4.jpg",
        color:"yellow",
        type:"tshirt",
        time:"new"
    },
    {
        Name: "swiftGrip"  ,
        fName: "s",
        id:6,
        amount:1,
        price:`${18}$`,
        img:"UpdatedImg/31c2f71c7b9646d5093a5fdc5323bfce.jpg",
        type:"shouse",
        color:"others",
        time:"old"
    },
    {
        Name: "vitaBlend" ,
        fName: "v",
        id:7,
        amount:1,
        price:`${90}$`,
        img:"UpdatedImg/424f57bfd66036837a883cf8ac78a162.jpg",
        type:"shouse",
        color:"browen",
        time:"new"
    },
    {
        Name: "glamEssence" ,
        fName: "g",
        id:8,
        amount:1,
        price:`${38}$`,
        img:"UpdatedImg/69925d9f2e0ac384fc962c03087d3e90.jpg",
        type:"others",
        color:"black",
        time:"new"
    },
        {
        Name: "trueSpark"  ,
        fName: "t",
        id:9,
        amount:1,
        price:`${176}$`,
        img:"UpdatedImg/615433ebcf774c69b71223bb12fe40b2.jpg",
        type:"tshirt",
        color:"black",
        time:"old",
    },
    {  
         Name: "solarLuxe"  ,
        fName: "s",
        id:10,
        amount:1,
        price:`${118}$`,
        img:"UpdatedImg/b373b79fa47dc63d46fba8cd9c22dcf9.jpg",
        type:"others",
        color:"black",
        time:"new",
    },
    {
        Name: "crystalWave",
        fName: "c",
        id:11,
        amount:1,
        price:`${90}$`,
        img:"UpdatedImg/c24a013e0e59e309b5625950ebb6de1d.jpg",
        type:"others",
        color:"others",
        time:"old",
    },
    {
        Name: "pureSilk"  ,
        fName: "p",
        id:12,
        amount:1,
        price:`${66}$`,
        img:"UpdatedImg/dc4125bbe15a9e95758d9c62d4a9d5fa.jpg",
        type:"jense",
        color:"others",
        time:"new"
    },
    {
        Name: "urbanEdge" ,
        fName: "u",
        id:13,
        amount:1,
        price:`${76}$`,
        img:"UpdatedImg/ddde149b1134c4387cd174a99b8d2e31.jpg",
        type:"hoddies",
        color:"white",
        time:"old"
    },
    {
        Name: "harmonyMist",
        fName: "h",
        id:14,
        amount:1,
        price:`${89}$`,
        img:"UpdatedImg/de4034f6d923ab77efd572526ddad90c.jpg",
        type:"hoddies",
        color:"black",
        time:"new",
    },
    {
        Name: "ecoThrive" ,
        fName: "e",
        id:15,
        amount:1,
        price:`${56}$`,
        img:"UpdatedImg/e6216c7e83cd1a4e7b536b06a059c967.jpg",
        type:"hoddies",
        color:"others",
        time:"old",
    },
    {
        Name: "blissGlow",
        fName: "b",
        id:16,
        amount:1,
        price:`${46}$`,
        img:"UpdatedImg/f6947e640421d97017f27f6e9f08db61.jpg",
        color:"black",
        time:"new",
    },
    {
        Name: "maxFlex",
        fName: "m",
        id:17,
        amount:1,
        price:`${32}$`,
        img:"UpdatedImg/photo_2024-01-30_08-23-27.jpg",
        type:"shouse",
        color:"white",
        time:"old",
    },
    {
        Name: "novaGlide" ,
        fName: "n",
        id:18,
        amount:1,
        price:`${26}$`,
        img:"UpdatedImg/photo_2024-01-30_08-23-32.jpg",
        color:"white",
        time:"new",
    },
    {
        Name: "pureVital"  ,
        fName: "p",
        id:19,
        amount:1,
        price:`${32}$`,
        img:"UpdatedImg/photo_2024-01-30_08-23-33.jpg",
        type:"shouse",
        color:"red",
        time:"old",
    },
    {
        Name: "techPulse" ,
        fName: "t",
        id:20,
        amount:1,
        price:`${26}$`,
        img:"UpdatedImg/photo_2024-01-30_08-23-35.jpg",
        type:"others",
        color:"white",
        time:"new",
    },

    {
        Name: "zenEco",
        id: 21,
        fName: "z",
        amount:1,
        price:`${52}$`,
        img:"additionall/6d50c202d34338ae3c4d0e5c3c74a859.jpg",
        type:"tshirt",
        color:"black",
        time:"old",
    },
    {
        Name: "aquaGlide",
        id: 22,
       fName: "a",
        amount:1,
        price:`${96}$`,
        img:"additionall/8c374fd1c49c49d5815397d17fda20b6.jpg",
        color:"others",
        type:"tshirt",
        time:"new",
    },
    {
        Name: "urbanSpark",
        id: 23,
        fName: "u",
        amount:1,
        price:`${32}$`,
        img:"additionall/9b2cd95efd227087d27809ecf11d2c11.jpg",
        type:"tshirt",
        color:"black",
        time:"old",
    },
    {
        Name: "novaPure",
        id: 24,
        fName: "n",
        amount:1,
        price:`${26}$`,
        img:"additionall/54e0eab5f049c149a5e95420c5bb2ccd.jpg",
        type:"others",
        color:"black",
        time:"new",
    },   

]
export default newDatas;














