import type { Metadata } from "next";
import { CountdownProvider } from '../context/CountdownContext';
import { UserProvider } from '../context/UserContext';
import Navbar from '../../components/Nav';

export const metadata: Metadata = {
  title: "Virtual health",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CountdownProvider>
      <UserProvider>
        <Navbar />
        {children}
      </UserProvider>
    </CountdownProvider>
  );
}